// import './instance/index'
// import './lifecyc/index'
// import './data-binding/index'
// import './computed/index'
// import './directive'
// import './component/define'
// import './component/extend'
// import './component/v-model'
import './component/features'
